cursor            #b2c5ff
cursor_text_color #172e60

foreground            #e2e2e9
background            #0d0e13
selection_foreground  #2a3042
selection_background  #c0c6dd
url_color             #c0c6dd

#: black 000000 767676
color0  #121318
color8  #33343a
#: red cc0403 f2201f
color1  #e123bf
color9  #f3aae6
#: green 19cb00 23fd00
color2  #c0c6dd
color10 #dce2f9
#: yellow cecb00 fffd00
color3  #e1bbdd
color11 #fed7f9
#: blue 0d73cc 1a8fff
color4  #304578
color12 #b2c5ff
#: magenta cb1ed1 fd28ff
color5  #404659
color13 #c0c6dd
#: cyan 0dcdcd 14ffff
color6  #5a3d59
color14 #e1bbdd
#: white dddddd ffffff
color7  #c5c6d0
color15 #e2e2e9

mark1_foreground #001847
mark1_background #dae2ff
mark2_foreground #151b2c
mark2_background #dce2f9
mark3_foreground #2b122c
mark3_background #fed7f9

active_tab_foreground #172e60
active_tab_background #b2c5ff
inactive_tab_foreground #dae2ff
inactive_tab_background #304578

active_border_color #b2c5ff
inactive_border_color #172e60
# bell_border_color #ff5a00
